### PR TITLE
Add ability to override where to redirect to after login/out

### PR DESCRIPTION
**Pull request by jcmuller**

### CODE REVIEW

**Comment by rossta** [comment]
Thanks, @jcmuller. Looks like a good change!

Could you get the build to pass? Also, could you change the names from `after_login/logout_redirect_to` to `after_login/logout_path`?

**Comment by jcmuller** [comment]
Changed! And fixed. Then Travis complained about too may octokit requests...

On Mon, Aug 10, 2015 at 2:46 PM, Ross Kaffenberger <notifications@github.com
> wrote:

> Thanks, @jcmuller <https://github.com/jcmuller>. Looks like a good change!
>
> Could you get the build to pass? Also, could you change the names from
> after_login/logout_redirect_to to after_login/logout_path?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rossta/opensesame/pull/8#issuecomment-129562321>.
>



-- 
Juan C.

**Comment by jcmuller** [comment]
Thanks for pulling, @rossta! Can you push to rubygems?

**Comment by rossta** [comment]
Done!

**Pull request merged**
